Repository bloom-works/co-care-directory, pull requests merged in 2022-07, with the labels that each got.

#52 misc polish: filter button, homepage cards
  src/components/Home/ContentCard.tsx
  src/components/Home/ZipCard.tsx
  src/components/Home/ZipInput.tsx
  src/components/Layout.tsx
  src/components/Search/Filters/Control.tsx
  src/index.css
  src/pages/GuidedSearch.tsx
  src/pages/Home.tsx
  src/pages/Search.tsx
  src/translations/en/common.json
  src/translations/en/pages.json
  src/util.tsx
Labels: release-patch

#55 Adds the default CodeQL config file
  .github/workflows/codeql-analysis.yml
Labels: release-patch

#56 Pre launch misc cleanup
  src/components/Footer.tsx
  src/components/Home/ZipCard.tsx
  src/components/ResultDetail/BasicResultDetail.tsx
  src/components/ResultDetail/ResultDatum.tsx
  src/components/Search/Filters/Control.tsx
  src/components/Search/Filters/DistanceInput.tsx
  src/components/Search/Filters/TypeOfHelpInput.tsx
  src/pages/Home.tsx
  src/translations/en/components.json
  src/util.tsx
Labels: release-patch

#57 content updates
  src/components/Footer.tsx
  src/pages/Search.tsx
  src/translations/en/common.json
  src/translations/en/components.json
  src/translations/en/pages.json
Labels: release-patch

#53 Staging/Production Setup Scripts
  README.md
  aws.tf
Labels: release-patch

#58 language detection
  package-lock.json
  package.json
  src/components/Footer.tsx
  src/i18n.ts
  src/translations/es/common.json
Labels: release-patch

#60 LADDERS Update - July 1, 2022
  raw_data/ladders.csv
  src/data/ladders_data.json
Labels: release-patch

#62 footer link fix
  src/components/Footer.tsx
Labels: release-patch

#61 Translations
  src/components/ResultDetail/Hours.tsx
  src/i18n.ts
  src/pages/Home.tsx
  src/pages/ResultDetail.tsx
  src/translations/en/components.json
  src/translations/en/pages.json
  src/translations/es/common.json
  src/translations/es/components.json
  src/translations/es/pages.json
Labels: release-patch

#64 Google Analytics for Production
  public/index.html
Labels: release-patch

#65 refactor zip validation + smarter default radius
  src/components/Home/ZipCard.tsx
  src/components/Home/ZipInput.tsx
  src/pages/GuidedSearch.tsx
  src/pages/Search.tsx
  src/translations/en/common.json
  src/types.ts
  src/util.test.tsx
  src/util.tsx
Labels: release-patch

#67 adding a few more translations
  src/translations/es/common.json
  src/translations/es/pages.json
Labels: release-patch

#68 more space efficient search results heading
  src/components/Search/MobileViewToggle.tsx
  src/pages/Search.tsx
  src/translations/en/pages.json
  src/translations/es/pages.json
Labels: release-patch

#69 Rerender map when filters are applied
  src/components/Search/Filters/Control.tsx
  src/pages/ResultDetail.tsx
  src/pages/Search.tsx
Labels: release-patch

#74 directions cleanup
  src/components/ResultDetail/BasicResultDetail.tsx
  src/components/ResultDetail/DirectionsLink.tsx
  src/pages/ResultDetail.tsx
  src/util.tsx
Labels: release-patch

#75 utils cleanup + adding tests for filter code
  src/util.test.tsx
  src/util.tsx
Labels: release-patch

#77 Cleanup and config for post-launch review/release process
  .github/CODEOWNERS
  .gitignore
  CONTRIBUTING.md
  README.create-react-app.md
  README.md
  package-lock.json
  package.json
  src/data/ladders_data.json
Labels: release-major

#85 switch to osm tiles
  src/components/Map.tsx
Labels: release-patch

#84 condensed hours display
  src/components/ResultDetail/Hours.tsx
  src/translations/en/common.json
  src/translations/en/components.json
  src/translations/es/common.json
  src/translations/es/components.json
Labels: release-patch

#72 Adds fees preference question to guided flow search
  src/components/Search/Filters/Control.tsx
  src/components/Search/Filters/FeePreferenceInput.tsx
  src/data/process_data.ts
  src/pages/GuidedSearch.tsx
  src/translations/en/pages.json
  src/translations/es/pages.json
  src/types.ts
  src/util.test.tsx
  src/util.tsx
Labels: release-patch

#87 analytics updates
  package-lock.json
  package.json
  public/index.html
  src/analytics.ts
  src/components/Search/Filters/AccessibilityInput.tsx
  src/components/Search/Filters/Control.tsx
  src/components/Search/Filters/DistanceInput.tsx
  src/components/Search/Filters/FeePreferenceInput.tsx
  src/components/Search/Filters/TypeOfHelpInput.tsx
  src/pages/GuidedSearch.tsx
  src/pages/Home.tsx
  src/pages/ResultDetail.tsx
  src/pages/Search.tsx
  src/pages/Whoops.tsx
Labels: release-patch

#86 Add share button to search results and result detail
  src/components/ShareButton.tsx
  src/images/share.svg
  src/pages/ResultDetail.tsx
  src/pages/Search.tsx
  src/translations/en/components.json
  src/translations/en/pages.json
  src/translations/es/components.json
  src/translations/es/pages.json
Labels: release-patch

#89 Bug Fix: Name of the Docker container is consistent
  README.md
Labels: release-patch

#81 Store Terraform State File Centrally
  .github/CODEOWNERS
  README.md
  infra/aws/infra/aws_infra.tf
  infra/aws/state/aws_state.tf
Labels: release-minor

#90 copy and styling fixes on search results page
  src/components/Search/Filters/Control.tsx
  src/pages/Search.tsx
Labels: release-patch

#92 Fixup misplaced translations for share button
  src/components/ShareButton.tsx
  src/translations/en/components.json
  src/translations/en/pages.json
  src/translations/es/components.json
  src/translations/es/pages.json
Labels: release-patch

#91 Incorporate LADDERS push 20220713-234002958
  raw_data/ladders.csv
  src/data/process_data.ts
  src/types.ts
  src/util.test.tsx
Labels: release-patch

#95 misc cleanup - fix warnings
  src/components/Search/Filters/Control.tsx
  src/components/Search/Filters/HoursInput.tsx
Labels: release-patch

#97 full-width search results page
  src/pages/Search.tsx
Labels: release-patch

#96 add language filter to search results
  src/components/Search/Filters/Control.tsx
  src/components/Search/Filters/LanguageInput.tsx
  src/translations/en/components.json
  src/translations/es/components.json
  src/types.ts
  src/util.test.tsx
  src/util.tsx
Labels: release-patch

#98 provider info polish
  src/components/ResultDetail/BasicResultDetail.tsx
  src/components/ResultDetail/DirectionsLink.tsx
  src/components/ResultDetail/Hours.tsx
  src/components/ResultDetail/ResultDatum.tsx
  src/components/Search/ResultCard.tsx
  src/pages/ResultDetail.tsx
  src/pages/Search.tsx
Labels: release-patch

#99 log page path to google analytics
  src/analytics.ts
Labels: release-patch
